version: "3.3"

services: 
  github-dynamic-changelog:
    image: comworkio/github-dynamic-changelog:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: api
  github-label-client:
    image: comworkio/github-label-client:latest
    build: 
      context: .
      dockerfile: Dockerfile
      target: label_client
