version: "3.3"

services: 
  cmd-api:
    image: comworkio/github-dynamic-changelog:latest
    user: root
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports: 
      - 8080:8080
