version: "3.3"

services: 
  github-dynamic-changelog:
    image: comworkio/github-dynamic-changelog:latest
    container_name: github-dynamic-changelog
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports: 
      - 8080:8080
